# Generated by Django 4.2 on 2023-06-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('total_hours_billed', models.IntegerField()),
                ('amount_billed', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('paid', models.CharField(max_length=10)),
                ('sent', models.CharField(max_length=10)),
            ],
        ),
    ]
