# Generated by Django 4.2 on 2023-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceTab', '0002_projectinformation_delete_projectdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
