# Generated by Django 4.2 on 2023-05-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceTab', '0004_projectinformation_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='costs_actual',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='costs_planned',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='margin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='project_value_planned',
            field=models.FloatField(null=True),
        ),
    ]
