# Generated by Django 4.2 on 2023-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceTab', '0006_remove_projectinformation_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='HRcost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='design',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='development',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='direct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='indirect',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='marketing',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='officeCost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='other',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='otherCosts',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='salesCosts',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='total_revenue',
            field=models.FloatField(null=True),
        ),
    ]
