# Generated by Django 4.2 on 2023-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceTab', '0006_remove_projectinformation_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
