# Generated by Django 4.2 on 2023-05-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceTab', '0006_remove_projectinformation_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinformation',
            name='team_size',
            field=models.IntegerField(default=0),
        ),
    ]
