# Generated by Django 4.2 on 2023-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceTab', '0007_alter_projectinformation_team_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinformation',
            name='team_size',
        ),
        migrations.AddField(
            model_name='projectinformation',
            name='team_s',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
